'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: "${{ matrix.os }}"
    steps:
      -
        uses: actions/checkout@v2
        with:
          lfs: true
      -
        uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
      -
        uses: actions-rs/toolchain@v1
        with:
          default: true
          profile: minimal
          toolchain: nightly
      -
        uses: actions-rs/cargo@v1
        with:
          args: "--release"
          command: build
      -
        id: get_repository_name
        run: "echo ::set-output name=REPOSITORY_NAME::$(echo \"$GITHUB_REPOSITORY\" | awk -F / '{print $2}' | sed -e \"s/:refs//\")"
        shell: bash
      -
        uses: actions/upload-artifact@v2
        with:
          name: "${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}-${{ matrix.target }}"
          path: "./target/release/${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}${{ matrix.suffix }}"
    strategy:
      matrix:
        include:
          -
            os: macos-latest
            suffix: ""
            target: x86_64-apple-darwin
          -
            os: ubuntu-latest
            suffix: ""
            target: x86_64-unknown-linux-gnu
          -
            os: windows-latest
            suffix: ".exe"
            target: x86_64-pc-windows-msvc
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          lfs: true
      -
        uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
      -
        uses: actions/download-artifact@v2
      -
        uses: actions-rs/toolchain@v1
        with:
          default: true
          profile: minimal
          toolchain: nightly
      -
        uses: actions-rs/cargo@v1
        with:
          args: toml-cli
          command: install
      -
        id: get_repository_name
        run: "echo ::set-output name=REPOSITORY_NAME::$(echo \"$GITHUB_REPOSITORY\" | awk -F / '{print $2}' | sed -e \"s/:refs//\")"
        shell: bash
      -
        id: get_version
        run: "echo ::set-output name=VERSION::v$(toml get Cargo.toml package.version | tail -c +2 | head -c -2)"
        shell: bash
      -
        env:
          GITHUB_TOKEN: "${{ secrets.COMMITTER_TOKEN }}"
        id: create_release
        uses: actions/create-release@v1.1.0
        with:
          draft: false
          prerelease: false
          release_name: "Release ${{ steps.get_version.outputs.VERSION }}"
          tag_name: "${{ steps.get_version.outputs.VERSION }}"
      -
        env:
          GITHUB_TOKEN: "${{ secrets.COMMITTER_TOKEN }}"
        uses: actions/upload-release-asset@v1.0.2
        with:
          asset_content_type: application/octet-stream
          asset_name: "${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}-x86_64-unknown-linux-gnu"
          asset_path: "./${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}-x86_64-unknown-linux-gnu/${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}"
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
      -
        env:
          GITHUB_TOKEN: "${{ secrets.COMMITTER_TOKEN }}"
        uses: actions/upload-release-asset@v1.0.2
        with:
          asset_content_type: application/octet-stream
          asset_name: "${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}-x86_64-apple-darwin"
          asset_path: "./${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}-x86_64-apple-darwin/${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}"
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
      -
        env:
          GITHUB_TOKEN: "${{ secrets.COMMITTER_TOKEN }}"
        uses: actions/upload-release-asset@v1.0.2
        with:
          asset_content_type: application/octet-stream
          asset_name: "${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}-x86_64-pc-windows-msvc"
          asset_path: "./${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}-x86_64-pc-windows-msvc/${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}.exe"
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
